all: single_select_local multi_select_local

single_select_local:
	cd .. && elm make examples/SingleSelectLocal/Main.elm --output=examples/Compiled/single_select_local.js

multi_select_local:
	cd .. && elm make examples/MultiSelectLocal/Main.elm --output=examples/Compiled/multi_select_local.js