all: single_select multi_select

single_select:
	cd .. && elm make examples/SingleSelect/Main.elm --output=examples/Compiled/single_select.js

multi_select:
	cd .. && elm make examples/MultiSelect/Main.elm --output=examples/Compiled/multi_select.js
