all: single multi

single:
	cd .. && elm make examples/SingleSelect/Main.elm --output=examples/Compiled/single.js

multi:
	cd .. && elm make examples/MultiSelect/Main.elm --output=examples/Compiled/multi.js